version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.14.1
    steps:
      - checkout
      - run: ls -larth
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run test
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - build

  publish:
    machine:
      enabled: true
    steps:
      - checkout
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "36:ad:64:7a:90:0e:02:4e:a7:e0:52:af:83:c9:f5:48"
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run: ls -larth
      - run:
          name: Push to github-pages
          no_output_timeout: 1m
          command: |
            git remote -v
            git config --global user.email "builds@circleci.com"
            git config --global user.name "CircleCI"
            npm run deploy:no-build

workflows:
  version: 2
  build-publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
